language: java
dist: trusty

env:
  global:
    - JAVA_TOOL_OPTIONS=-Dhttps.protocols=TLSv1.2

script: ./gradlew build --full-stacktrace

jdk:
  - openjdk21

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

notifications:
  slack: reportportal:fl6xWHVQp1jvsMmCJxYW9YKP
